// frontend/src/pages/LoginView.tsx
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { useNavigate } from "react-router-dom";

export default function LoginView() {
  const navigate = useNavigate();

  const [error, setError] = useState<string>('')
  const [username, setUsername] = useState<string>('')
  const [password, setPassword] = useState<string>('')

  const validateForm = (): boolean => {
    if (!username || !password) {
      setError("Fields are missing");
      return false;
    }

    setError("");
    return true;
  }

  const handleLogin = async () => {
    if (!validateForm()) {
      return;
    }

    const user = {
      username: username,
      password: password
    }

    try {
      const response = await fetch("/api/login", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          user: user.username,
          password: user.password
        }),
      });

      const data = await response.json();
      if (response.status !== 200) {
        setError("Username or password are incorrect!");
        return;
      }

      localStorage.setItem("token", data.token);
      localStorage.setItem("user", JSON.stringify(data.user));

      navigate("/");
    } catch (err) {
      setError("Something went wrong, try again later.");
    };
  }

  return (
    <div className="flex items-center justify-center min-h-screen bg-stone-900 font-sans">
      <Card className="w-full max-w-sm bg-stone-800 text-white border-stone-700 shadow-xl rounded-2xl">
        <CardHeader>
          <h2 className="text-2xl font-semibold text-center">Login</h2>
        </CardHeader>

        <CardContent>
          <form
            className="space-y-4"
            onSubmit={(e) => {
              e.preventDefault();
            }}
          >
            <div>
              <label className="block mb-2 text-stone-400">Username</label>
              <input
                type="text"
                placeholder="Username"
                className="w-full px-3 py-2 rounded-lg bg-stone-700 text-white placeholder-stone-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
            </div>

            <div>
              <label className="block mb-2 text-stone-400">Password</label>
              <input
                type="password"
                placeholder="Password"
                className="w-full px-3 py-2 rounded-lg bg-stone-700 text-white placeholder-stone-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>

            {error && (
              <p className="text-red-500 text-sm mt-2 text-center">{error}</p>
            )}

            <Button
              type="submit"
              className="w-full bg-blue-600 hover:bg-blue-700 font-semibold mt-4"
              onClick={handleLogin}
            >
              Login
            </Button>
          </form>
        </CardContent>

        <CardFooter className="flex justify-center">
          <p className="text-stone-400 text-sm">
            Don't have an account?{" "}
            <a href="/register" className="text-blue-500 hover:underline">
              Register
            </a>
          </p>
        </CardFooter>
      </Card>
    </div>
  );
}

// frontend/src/views/LoginView.vue
<template>
  <div class="flex items-center justify-center min-h-screen bg-stone-900 font-sans">
    <Card class="w-full max-w-sm bg-stone-800 text-white border-stone-700 shadow-xl rounded-2xl">
      <CardHeader>
        <h2 class="text-2xl font-semibold text-center">Login</h2>
      </CardHeader>

      <CardContent>
        <form @submit.prevent="handleLogin" class="space-y-4">
          <div>
            <label for="user" class="block mb-2 text-stone-400">Username</label>
            <input id="user" type="text" v-model="username" placeholder="Username"
              class="w-full px-3 py-2 rounded-lg bg-stone-700 text-white placeholder-stone-500 focus:outline-none focus:ring-2 focus:ring-blue-500" />
          </div>

          <div>
            <label for="password" class="block mb-2 text-stone-400">Password</label>
            <input id="password" type="password" v-model="password" placeholder="Password"
              class="w-full px-3 py-2 rounded-lg bg-stone-700 text-white placeholder-stone-500 focus:outline-none focus:ring-2 focus:ring-blue-500" />
          </div>

          <p v-if="errorMessage" class="text-red-500 text-center text-sm">
            {{ errorMessage }}
          </p>

          <Button type="submit" class="w-full bg-blue-600 hover:bg-blue-700 font-semibold">
            Login
          </Button>
        </form>
      </CardContent>

      <CardFooter class="flex justify-center mt-2">
        <p class="text-stone-400 text-sm">
          Don't have an account?
          <a href="register" class="text-blue-500 hover:underline">Register</a>
        </p>
      </CardFooter>
    </Card>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import { ref } from 'vue';
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const router = useRouter();

const username = ref('');
const password = ref('');
const errorMessage = ref('');

const handleErrors = (): boolean => {
  errorMessage.value = '';

  if (!username.value) {
    errorMessage.value = 'Username is required!';
    return false;
  }

  if (!password.value) {
    errorMessage.value = 'Password is required!';
    return false;
  }

  return true;
}

const handleLogin = async () => {
  if(!handleErrors()){
    return;
  }

  let response = await fetch("/api/login", {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({user: username.value, password: password.value})
  });

  let data = await response.json();

  if(response.status != 200){
    errorMessage.value = 'Username or password are incorrect!'
    return;
  }
  localStorage.setItem('token', data.token)
  localStorage.setItem('user', JSON.stringify(data.user))

  router.push('/');
};
</script>
